In [1]:
import pandas as pd
import numpy as np
import streamlit as st
import altair as alt
from datetime import datetime as dt

In [2]:
file = 'Equipment_and_Metrology_Database.xlsx'
excel = pd.read_excel('Equipment_and_Metrology_Database.xlsx',index_col='ID #')
temp = pd.DataFrame(excel)
temp.head()

,Location,Type,Brand / Component,Model #,Serial #,Description,Specifications,Cal. Date,Cal. due Date,Qual_Freq,OQ/PQ PM SOP,PM Date,PM Date Next,Comment,Owner,Column2
ID #,,,,,,,,,,,,,,,,
50PROBE01,QC Lab,Thermometer,Traceable,651,210152050,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16 00:00:00,2024-11-30 00:00:00,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE02,QC Lab,Thermometer,Traceable,651,210151995,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16 00:00:00,2024-11-30 00:00:00,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE03,QC Lab,Thermometer,Traceable,651,210152045,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16 00:00:00,2024-11-30 00:00:00,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE04,QC Lab,Thermometer,Traceable,651,210152019,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16 00:00:00,2024-11-30 00:00:00,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE05,QC Lab,Thermometer,Traceable,651,210152052,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16 00:00:00,2024-11-30 00:00:00,Annual,NaN,NaN,NaN,NaN,Andy,NaN

In [3]:
temp.columns

Index(['Location', 'Type', 'Brand / Component', 'Model #', 'Serial #',
       'Description', 'Specifications', 'Cal. Date', 'Cal. due Date',
       'Qual_Freq', 'OQ/PQ PM SOP', 'PM Date', 'PM Date Next', 'Comment',
       'Owner', 'Column2'],
      dtype='object')

In [4]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 211 entries, 50PROBE01 to nan
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Location           210 non-null    object
 1   Type               210 non-null    object
 2   Brand / Component  206 non-null    object
 3   Model #            200 non-null    object
 4   Serial #           207 non-null    object
 5   Description        208 non-null    object
 6   Specifications     8 non-null      object
 7   Cal. Date          160 non-null    object
 8   Cal. due Date      166 non-null    object
 9   Qual_Freq          175 non-null    object
 10  OQ/PQ PM SOP       130 non-null    object
 11  PM Date            1 non-null      object
 12  PM Date Next       0 non-null      float64
 13  Comment            0 non-null      float64
 14  Owner              118 non-null    object
 15  Column2            0 non-null      float64
dtypes: float64(3), object(13)
memory usage: 28.0+ KB

In [5]:
tests = temp['Cal. Date'].astype(str)
dates = []
for test in tests:
    dates.append(test[:-9])
temp['Cal. Date']=dates
temp.head()

,Location,Type,Brand / Component,Model #,Serial #,Description,Specifications,Cal. Date,Cal. due Date,Qual_Freq,OQ/PQ PM SOP,PM Date,PM Date Next,Comment,Owner,Column2
ID #,,,,,,,,,,,,,,,,
50PROBE01,QC Lab,Thermometer,Traceable,651,210152050,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16,2024-11-30 00:00:00,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE02,QC Lab,Thermometer,Traceable,651,210151995,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16,2024-11-30 00:00:00,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE03,QC Lab,Thermometer,Traceable,651,210152045,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16,2024-11-30 00:00:00,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE04,QC Lab,Thermometer,Traceable,651,210152019,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16,2024-11-30 00:00:00,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE05,QC Lab,Thermometer,Traceable,651,210152052,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16,2024-11-30 00:00:00,Annual,NaN,NaN,NaN,NaN,Andy,NaN

In [6]:
date = temp['Cal. due Date'].astype(str)
why = []
for date in date:
    why.append(date[:-9])
temp['Cal. due Date'] = why
temp.head()

,Location,Type,Brand / Component,Model #,Serial #,Description,Specifications,Cal. Date,Cal. due Date,Qual_Freq,OQ/PQ PM SOP,PM Date,PM Date Next,Comment,Owner,Column2
ID #,,,,,,,,,,,,,,,,
50PROBE01,QC Lab,Thermometer,Traceable,651,210152050,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16,2024-11-30,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE02,QC Lab,Thermometer,Traceable,651,210151995,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16,2024-11-30,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE03,QC Lab,Thermometer,Traceable,651,210152045,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16,2024-11-30,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE04,QC Lab,Thermometer,Traceable,651,210152019,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16,2024-11-30,Annual,NaN,NaN,NaN,NaN,Andy,NaN
50PROBE05,QC Lab,Thermometer,Traceable,651,210152052,Ultra-Low Temperature WIFI Data Logger,NaN,2023-11-16,2024-11-30,Annual,NaN,NaN,NaN,NaN,Andy,NaN

In [7]:
temp.columns

Index(['Location', 'Type', 'Brand / Component', 'Model #', 'Serial #',
       'Description', 'Specifications', 'Cal. Date', 'Cal. due Date',
       'Qual_Freq', 'OQ/PQ PM SOP', 'PM Date', 'PM Date Next', 'Comment',
       'Owner', 'Column2'],
      dtype='object')

In [8]:
temp = temp.loc[:,['Location', 'Type', 'Serial #', 'Description', 'Cal. Date', 'Cal. due Date',
                   'Comment', 'Owner']]
temp.head()

,Location,Type,Serial #,Description,Cal. Date,Cal. due Date,Comment,Owner
ID #,,,,,,,,
50PROBE01,QC Lab,Thermometer,210152050,Ultra-Low Temperature WIFI Data Logger,2023-11-16,2024-11-30,NaN,Andy
50PROBE02,QC Lab,Thermometer,210151995,Ultra-Low Temperature WIFI Data Logger,2023-11-16,2024-11-30,NaN,Andy
50PROBE03,QC Lab,Thermometer,210152045,Ultra-Low Temperature WIFI Data Logger,2023-11-16,2024-11-30,NaN,Andy
50PROBE04,QC Lab,Thermometer,210152019,Ultra-Low Temperature WIFI Data Logger,2023-11-16,2024-11-30,NaN,Andy
50PROBE05,QC Lab,Thermometer,210152052,Ultra-Low Temperature WIFI Data Logger,2023-11-16,2024-11-30,NaN,Andy

In [9]:
temp.head()

,Location,Type,Serial #,Description,Cal. Date,Cal. due Date,Comment,Owner
ID #,,,,,,,,
50PROBE01,QC Lab,Thermometer,210152050,Ultra-Low Temperature WIFI Data Logger,2023-11-16,2024-11-30,NaN,Andy
50PROBE02,QC Lab,Thermometer,210151995,Ultra-Low Temperature WIFI Data Logger,2023-11-16,2024-11-30,NaN,Andy
50PROBE03,QC Lab,Thermometer,210152045,Ultra-Low Temperature WIFI Data Logger,2023-11-16,2024-11-30,NaN,Andy
50PROBE04,QC Lab,Thermometer,210152019,Ultra-Low Temperature WIFI Data Logger,2023-11-16,2024-11-30,NaN,Andy
50PROBE05,QC Lab,Thermometer,210152052,Ultra-Low Temperature WIFI Data Logger,2023-11-16,2024-11-30,NaN,Andy

In [10]:
temp.to_excel(file, index=False)